homebrew:
  taps:
    - "felixkratz/formulae"
    - "nikitabobko/tap"
    - "qmk/qmk"
  casks:
    - "wezterm"
    - "ghostty"
    - "shortcat"
    - "vlc"
    - "nikitabobko/tap/aerospace"
  packages:
    # Essentials
    - "zsh"
    - "fish"
    - "bash"
    - "neovim"
    - "ansible"
    - "docker"
    - "wget"
    - "ollama"
    - "gnu-sed"
    - "gnupg"
    - "tmux"
    - "felixkratz/formulae/sketchybar"
    - "felixkratz/formulae/borders"
    - "watch"
    - "qmk/qmk/qmk"
    - "uv"
    - "fastfetch"

    # Compiler/Runtime
    - "go"
    - "rust"
    - "bun"
    - "postgresql"

    # Dependencies Management
    - "pnpm"
    - "fisher"

    # Tools
    - "htop"
    - "jq"
    - "fd"
    - "ripgrep"
    - "git"
    - "starship"
    - "bat"
    - "eza"
    - "ffmpeg"
    - "fzf"
    - "imagemagick"
    - "hyperfine"
    - "yazi"
    - "zoxide"
    - "coreutils"
    - "moreutils"
    - "cyme"
    - "make"
    - "graphviz"
    - "xz"
    - "git-lfs"
    - "just"
