#!/usr/bin/env bash

# Theme
set -g status-position bottom

set -g mode-style "fg=#c9d1d9,bg=#2d3540"
set -g status-style "fg=gray,bg=#2d3540"
set -g status-left-style NONE
# set -g status-right-style NONE

setw -g monitor-activity off
set -g visual-activity off

set -g status-justify left
set -g status-left "#[fg=0,bg=#{?copy_cursor_line,3,2},bold]    #[default] "
setw -g status-left-length 120
# set -g status-right "#[fg=yellow,bg=default,bold]  %I:%M %p "
# set -g status-right ""

setw -g window-status-style "fg=#c9d1d9,bg=default"
setw -g window-status-separator " #[fg=7,dim]|#[default] "
# setw -g window-status-format "#[fg=DarkGray,bg=default] #W (#I)"
# setw -g window-status-current-format "#[bold,fg=lightgreen,bg=default] #W (#I)"
# setw -g window-status-current-format "#[bold,fg=#fa7a61,bg=default]  #W"
#setw -g window-status-current-format "#[bold,fg=#fa7a61,bg=default]  #W"
setw -g window-status-current-format " #[bold,fg=3,bg=default]  #W "
setw -g window-status-format " #[fg=7,dim,bg=default]  #W "

# Pane border
set -g pane-border-style "fg=#1e293b"
set -g pane-active-border-style "fg=#1e293b"
#set -g pane-active-border-style "fg=#334155"
set -g window-active-style 'fg=terminal,bg=terminal'
#set -g window-style 'fg=#686F7D bg=terminal'
set -g window-style 'fg=#64748b,bg=terminal'

set -g message-style "bg=2,fg=0"
