#!/usr/bin/env bash

# colors
background="terminal"
gray_dark="#2d3540"
gray_muted="gray"
gray_light="#c9d1d9"
border="#1e293b"
text_muted="#64748b"

# Theme
set -g status-position top

set -g mode-style "fg=${gray_light},bg=${gray_dark}"
set -g status-style "fg=${gray_muted},bg=${background}"
# set -g status-left-style NONE
# set -g status-right-style NONE

setw -g monitor-activity off
set -g visual-activity off

set -g status-justify left
set -g status-left "#[fg=${gray_dark},bg=#{?copy_cursor_line,3,2},bold]   #S  #[default] "
setw -g status-left-length 120
# set -g status-right "#[fg=yellow,bg=default,bold]  %I:%M %p "
# set -g status-right ""

setw -g window-status-style "fg=${gray_light},bg=${background}"
setw -g window-status-separator " #[fg=7,dim]|#[default] "
setw -g window-status-current-format " #[bold,fg=3,bg=${background}]  #W "
setw -g window-status-format " #[fg=${gray_muted},dim,bg=${background}]  #W "

# Pane border
set -g pane-border-style "fg=${border}"
set -g pane-active-border-style "fg=${text_muted}"
set -g window-active-style "fg=${background},bg=${background}"
set -g window-style "fg=${text_muted},bg=${background}"

# Display messages
set -g message-style "bg=2,fg=0,bold"
