# Leader
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Force use of zsh
set-option -g default-shell /bin/zsh

# Termcolor
set -g default-terminal "xterm-256color"
set -as terminal-overrides ",xterm*:Tc"
set-option -ga terminal-overrides ",xterm-256color:Tc"
set -as terminal-features ",xterm-256color:RGBA"

# Split panes
unbind %
unbind d
# bind d split-window -v

unbind h
# bind h split-window -h

# Kill pane
unbind x
unbind z
bind x kill-pane
bind z kill-pane

# Refresh tmux config
unbind r
bind r source-file "~/.config/tmux/tmux.conf"


bind f split-window -c "#{pane_current_path}"
bind d split-window -h -c "#{pane_current_path}"

bind -r j resize-pane -L 5
bind -r k resize-pane -U 5
bind -r l resize-pane -D 5
bind -r m resize-pane -R 5


# Maximize pane
unbind ù
bind -r ù resize-pane -Z

# Enable mouse
set -g mouse on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'sunaku/tmux-navigate'
set -g @plugin 'jimeh/tmuxifier'

# Navigation keymap
set -g @navigate-left '-n C-j'
set -g @navigate-up '-n C-k'
set -g @navigate-down '-n C-l'
set -g @navigate-right '-n C-h'

# Clear screen
bind -n C-g send-keys "clear" \; send-keys "Enter" \; clear-history

# Restore last session
set -g @continuum-restore 'on'

# Keep at the very end
run "~/.config/tmux/plugins/tpm/tpm"
source-file "~/.config/tmux/theme.conf"

