#!/usr/bin/env bash

# 'exec-and-forget borders ax_focus=off active_color="gradient(top_left=0xfffa7a61,bottom_right=0xffBD5EFF" style=round inactive_color="0x00FFFFFF" width=6.0 hidpi=on blur_radius=0.0 order=above'

source "$XDG_CONFIG_HOME/colors/colors.sh"
options=(
  ax_focus=on
  active_color="gradient(top_right=$ALT400,bottom_left=$BRAND400)"
  style=round
  inactive_color="0x00FFFFFF"
  width=2.0
  hidpi=off
  order=above
)

options2=(
  ax_focus=on
  active_color="gradient(top_left=0x40000000,bottom_right=0x00000000)"
  style=round
  inactive_color="0x00FFFFFF"
  width=16.0
  hidpi=off
  order=below
  )

borders "${options[@]}" & \
borders "${options2[@]}"
