#!/usr/bin/env bash

# 'exec-and-forget borders ax_focus=off active_color="gradient(top_left=0xfffa7a61,bottom_right=0xffBD5EFF" style=round inactive_color="0x00FFFFFF" width=6.0 hidpi=on blur_radius=0.0 order=above'

source "$XDG_CONFIG_HOME/colors/colors.sh"
options=(
  ax_focus=false
  # active_color="$BRAND400"
  # width=2.0
  # active_color="0xC8171717"
  active_color="0xF8FF834C"
  width=12.0
  style=round
  # inactive_color="0x5A171717"
  inactive_color="0x5A0F111A"
  hidpi=false
  order=below
  show_background=false
)
borders "${options[@]}"

# options2=(
#   ax_focus=on
#   active_color="gradient(top_left=0x40000000,bottom_right=0x00000000)"
#   style=round
#   inactive_color="0x00FFFFFF"
#   width=8.0
#   hidpi=off
#   order=below
# )
#
# borders "${options[@]}" &
# borders "${options2[@]}"
