#!/usr/bin/env bash

# 'exec-and-forget borders ax_focus=off active_color="gradient(top_left=0xfffa7a61,bottom_right=0xffBD5EFF" style=round inactive_color="0x00FFFFFF" width=6.0 hidpi=on blur_radius=0.0 order=above'

source "$XDG_CONFIG_HOME/colors/colors.sh"
options=(
  ax_focus=off
  active_color="gradient(top_left=$ALT500,bottom_right=$BRAND400)"
  style=round
  inactive_color="0x00FFFFFF"
  width=8.0
  hidpi=on
  order=above
)

borders "${options[@]}"
