#!/bin/sh

# Variable definitions
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items/floating"
SCRIPTS_DIR="$CONFIG_DIR/scripts"

source "$CONFIG_DIR/constants.sh"

##### Hot reload ####
sketchybar --hotload true

##### Bar Appearance #####
bar=(
  height=56
  position=top
  color=0x00171717
  sticky=on
  shadow=off
  blur_radius=0
  padding_left=24
  padding_right=24
  topmost=false
  notch_width=0
)
sketchybar --bar "${bar[@]}"

##### Changing Defaults #####
defaults=(
  updates=when_shown
  padding_right=8
  padding_left=8
  icon.font="$FONT:Bold:16.0"
  icon.color=$LABEL
  icon.padding_left=4
  icon.padding_right=4
  label.font="$FONT:Regular:13.0"
  label.color=$LABEL
  label.padding_left=4
  label.padding_right=4
  background.height=26
  background.corner_radius=8
  popup.background.border_width=2
  popup.background.corner_radius=8
  popup.background.border_color=$WHITE
  popup.background.color=$BLACK
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)
sketchybar --default "${default[@]}"

##### Adding Left Items #####
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/modes.sh"
source "$ITEM_DIR/front_app.sh"

##### Adding Center Items #####
source "$ITEM_DIR/notch.sh"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update

