#!/bin/sh

# Variable definitions
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"
SCRIPTS_DIR="$CONFIG_DIR/scripts"

source "$CONFIG_DIR/constants.sh"

##### Hot reload ####
sketchybar --hotload true

##### Bar Appearance #####
bar=(
  height=26
  position=top
  color=0x80171717
  sticky=on
  shadow=off
  blur_radius=24
  padding_left=8
  padding_right=8
  notch_width=0
  topmost=false
)
sketchybar --bar "${bar[@]}"

##### Changing Defaults #####
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:16.0"
  icon.color=$LABEL
  icon.padding_left=4
  icon.padding_right=4
  label.font="$FONT:Regular:13.0"
  label.color=$LABEL
  label.padding_left=4
  label.padding_right=4
  padding_right=4
  padding_left=4
  background.height=32
  background.corner_radius=9
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$WHITE
  popup.background.color=$BLACK
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)
sketchybar --default "${default[@]}"

##### Adding Left Items #####
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/modes.sh"
source "$ITEM_DIR/front_app.sh"

##### Adding Right Items #####
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/music.sh"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update


##### Trigger borders
borders=(
  ax_focus=on
  active_color="gradient(top_left=$BRAND,bottom_right=$MAUVE)"
  style=round
  inactive_color="0x00FFFFFF"
  width=6.0
  hidpi=on
  blur_radius=0.0
  order=above
)
borders "${borders[@]}"

